### ISSUE TITLE
run time error

### ISSUE THREAD

**Issue by hephaex** [TigerCompany-tigris/tigris-user-service#4]
## run command 
```
curl -X POST http://localhost:5000/mecab/v1/parse-ko-dic \
       -H "Content-type: application/json" \
       -d '{"sentence": "함수형 프로그래밍"}'
```
## error occur
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/api/server.py", line 16, in parse
    results = mecab_parse(sentence)
  File "/opt/api/server.py", line 49, in mecab_parse
    m = MeCab.Tagger('-d ' + dic_dir + dic_name)
  File "/usr/local/lib/python3.5/dist-packages/MeCab.py", line 307, in __init__
    this = _MeCab.new_Tagger(*args)
RuntimeError
```

**Comment by hephaex** [comment]
```
curl -X POST http://localhost:5000/mecab/v1/parse-ko-dic    -H "Content-type: application/json"    -d '{"sentence": "아름다운 우리말을 사 용합니다"}'|jq .
```

```
{
  "dict": "ko-dic",
  "message": "Success",
  "results": [
    {
      " ": "아름답/VA/*+ᆫ/ETM/*",
      "원형": "ETM",
      "품사": "VA+ETM",
      "품사-세분류1": "*",
      "품사-세분류2": "T",
      "품사-세분류3": "아름다운",
      "형태소": "아름다운",
      "활용구": "VA",
      "활용형": "Inflect"
    },
    {
      " ": "우리/NNG/*+말/NNG/*",
      "원형": "*",
      "품사": "NNG",
      "품사-세분류1": "*",
      "품사-세분류2": "T",
      "품사-세분류3": "우리말",
      "형태소": "우리말",
      "활용구": "*",
      "활용형": "Compound"
    },
    {
      " ": "*",
      "원형": "*",
      "품사": "JKO",
      "품사-세분류1": "*",
      "품사-세분류2": "T",
      "품사-세분류3": "을",
      "형태소": "을",
      "활용구": "*",
      "활용형": "*"
    },
    {
      " ": "*",
      "원형": "*",
      "품사": "NNG",
      "품사-세분류1": "*",
      "품사-세분류2": "T",
      "품사-세분류3": "사용",
      "형태소": "사용",
      "활용구": "*",
      "활용형": "*"
    },
    {
      " ": "하/XSV/*+ᄇ니다/EC/*",
      "원형": "EC",
      "품사": "XSV+EC",
      "품사-세분류1": "*",
      "품사-세분류2": "F",
      "품사-세분류3": "합니다",
      "형태소": "합니다",
      "활용구": "XSV",
      "활용형": "Inflect"
    }
  ],
  "status": 200
}
```
